package ma.ingenius.model;
// Generated Sep 6, 2016 12:52:49 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Activite generated by hbm2java
 */
@Entity
@Table(name = "ACTIVITE")
public class Activite implements java.io.Serializable {

	private Long idactivite;
	private Utilisateur utilisateur;
	private Projet projet;
	private Long quantite;
	private String commentaire;
	private Long dat;

	public Activite() {
	}

	public Activite(Long idactivite) {
		this.idactivite = idactivite;
	}

	public Activite(Long idactivite, Utilisateur utilisateur, Projet projet, Long quantite,
			String commentaire, Long dat) {
		this.idactivite = idactivite;
		this.utilisateur = utilisateur;
		this.projet = projet;
		this.quantite = quantite;
		this.commentaire = commentaire;
		this.dat = dat;
	}

	@Id

	@Column(name = "IDACTIVITE", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdactivite() {
		return this.idactivite;
	}

	public void setIdactivite(Long idactivite) {
		this.idactivite = idactivite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UTILISATEUR")
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJET")
	public Projet getProjet() {
		return this.projet;
	}

	public void setProjet(Projet projet) {
		this.projet = projet;
	}

	@Column(name = "QUANTITE", precision = 22, scale = 0)
	public Long getQuantite() {
		return this.quantite;
	}

	public void setQuantite(Long quantite) {
		this.quantite = quantite;
	}

	@Column(name = "COMMENTAIRE", length = 4000)
	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	@Column(name = "DAT", precision = 22, scale = 0)
	public Long getDat() {
		return this.dat;
	}

	public void setDat(Long dat) {
		this.dat = dat;
	}

}
