package ma.ingenius.model;
// Generated Sep 6, 2016 12:52:49 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Projet generated by hbm2java
 */
@Entity
@Table(name = "PROJET")
public class Projet implements java.io.Serializable {

	private Long idprojet;
	private String nom;
	private Set<Activite> activites = new HashSet<Activite>(0);

	public Projet() {
	}

	public Projet(Long idprojet) {
		this.idprojet = idprojet;
	}

	public Projet(Long idprojet, String nom, Set<Activite> activites) {
		this.idprojet = idprojet;
		this.nom = nom;
		this.activites = activites;
	}

	@Id

	@Column(name = "IDPROJET", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdprojet() {
		return this.idprojet;
	}

	public void setIdprojet(Long idprojet) {
		this.idprojet = idprojet;
	}

	@Column(name = "NOM", length = 4000)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projet")
	public Set<Activite> getActivites() {
		return this.activites;
	}

	public void setActivites(Set<Activite> activites) {
		this.activites = activites;
	}

}
