package ma.ingenius.model;
// Generated Sep 6, 2016 12:52:49 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "UTILISATEUR")
public class Utilisateur implements java.io.Serializable {

	private Long idutilisateur;
	private String email;
	private String nom;
	private String prenom;
	private String login;
	private String password;
	private Set<Activite> activites = new HashSet<Activite>(0);

	public Utilisateur() {
	}

	public Utilisateur(Long idutilisateur) {
		this.idutilisateur = idutilisateur;
	}

	public Utilisateur(Long idutilisateur, String email, String nom, String prenom, String login, String password,
			Set<Activite> activites) {
		this.idutilisateur = idutilisateur;
		this.email = email;
		this.nom = nom;
		this.prenom = prenom;
		this.login = login;
		this.password = password;
		this.activites = activites;
	}

	@Id

	@Column(name = "IDUTILISATEUR", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdutilisateur() {
		return this.idutilisateur;
	}

	public void setIdutilisateur(Long idutilisateur) {
		this.idutilisateur = idutilisateur;
	}

	@Column(name = "EMAIL", length = 4000)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "NOM", length = 4000)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", length = 4000)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "LOGIN", length = 4000)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "PASSWORD", length = 4000)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set<Activite> getActivites() {
		return this.activites;
	}

	public void setActivites(Set<Activite> activites) {
		this.activites = activites;
	}

}
